/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// For the list of available Workbox modules, or add any other
// Code you'd like.
// You can also remove this file if you'd prefer not to use a
// Service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import {
  precacheAndRoute,
  createHandlerBoundToURL,
  matchPrecache,
} from 'workbox-precaching';
import {
  registerRoute,
  NavigationRoute,
  setCatchHandler,
} from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

clientsClaim();

/**
 * We are not wrapping it in a 'message' event as per the new update.
 * @see https://developers.google.com/web/tools/workbox/modules/workbox-core
 */
self.skipWaiting();

/**
 * Precache all of the assets generated by your build process.
 * Their URLs are injected into the manifest variable below.
 * This variable must be present somewhere in your service worker file,
 * even if you decide not to use precaching. See https://cra.link/PWA
 */
precacheAndRoute(self.__WB_MANIFEST);

// This assumes /app-shell.html has been precached.

const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler);
registerRoute(navigationRoute);

// RegisterRoute(  'http://localhost:8000/todos',  workbox.strategies.networkFirst())

// Cache the Google Fonts stylesheets with a stale-while-revalidate strategy.
// @see https://developers.google.com/web/tools/workbox/guides/common-recipes#google_fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

registerRoute(
  ({ url }) =>
    url.origin ===
    'https://api.mapbox.com/styles/v1/ivanrt/ckdk80nes0wb01iqminlchno4?access_token=pk.eyJ1IjoiaXZhbnJ0IiwiYSI6ImNrZGlwN3B6ejA3M3QycnAzZHR4NWxnMXIifQ.wXvdCl_qPQ55hb8Bgkeb5A',
  new StaleWhileRevalidate({
    cacheName: 'mapbox-api-cache',
  })
);

registerRoute(
  ({ url }) =>
    url.origin ===
    'https://events.mapbox.com/events/v2?access_token=pk.eyJ1IjoiaXZhbnJ0IiwiYSI6ImNrZGlwN3B6ejA3M3QycnAzZHR4NWxnMXIifQ.wXvdCl_qPQ55hb8Bgkeb5A',
  new StaleWhileRevalidate({
    cacheName: 'mapbox-event-cache',
  })
);

// Cache the underlying font files with a cache-first strategy for 1 year.
// @see https://developers.google.com/web/tools/workbox/guides/common-recipes#google_fonts
registerRoute(
  ({ url }) =>
    url.origin ===
    `https://events.mapbox.com/events/v2?access_token=${process.env.mapboxToken}`,
  new CacheFirst({
    cacheName: 'map-box-utility-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365,
        maxEntries: 30,
      }),
    ],
  })
);

// Cache the underlying font files with a cache-first strategy for 1 year.
// @see https://developers.google.com/web/tools/workbox/guides/common-recipes#google_fonts
registerRoute(
  ({ url }) =>
    url.origin ===
    `https://api.mapbox.com/styles/v1/ivanrt/ckdk80nes0wb01iqminlchno4?access_token=${process.env.mapboxToken}`,
  new CacheFirst({
    cacheName: 'map-box-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365,
        maxEntries: 30,
      }),
    ],
  })
);

// Cache the underlying font files with a cache-first strategy for 1 year.
// @see https://developers.google.com/web/tools/workbox/guides/common-recipes#google_fonts
registerRoute(
  ({ url }) =>
    url.origin ===
    `https://api.mapbox.com/styles/v1/ivanrt/ckdk80nes0wb01iqminlchno4?access_token=pk.eyJ1IjoiaXZhbnJ0IiwiYSI6ImNrZGlwN3B6ejA3M3QycnAzZHR4NWxnMXIifQ.wXvdCl_qPQ55hb8Bgkeb5A`,
  new CacheFirst({
    cacheName: 'map-box-cached-assets',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365,
        maxEntries: 30,
      }),
    ],
  })
);

/**
 * Countries list api.
 *
 * Caches at: runtime
 */
registerRoute(
  ({ url }) =>
    url.origin ===
      `${process.env.API_BASE_URL?.toString().slice(
        0,
        Math.max(0, process.env.API_BASE_URL.length - 1)
      )}` && url.pathname.startsWith('/api/locations/countries/'),

  new StaleWhileRevalidate({
    cacheName: 'countries-api',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({ maxEntries: 200 }), // Will cache maximum 1 requests.
    ],
  })
);

new RegExp('/styles/.*\\.css'),
  /**
   * Country Boundary api.
   *
   * Caches at: runtime
   */
  registerRoute(
    ({ url }) =>
      url.origin ===
        `${process.env.API_BASE_URL?.toString().slice(
          0,
          Math.max(0, process.env.API_BASE_URL.length - 1)
        )}` && url.pathname.startsWith('/api/locations/countries-boundary/'),

    new StaleWhileRevalidate({
      cacheName: 'country_boundary-api',
      plugins: [
        new CacheableResponsePlugin({
          statuses: [0, 200],
        }),
        new ExpirationPlugin({ maxEntries: 1 }), // Will cache maximum 1 requests.
      ],
    })
  );

/**
 * Global Statistics api.
 *
 * Caches at: runtime
 */
registerRoute(
  ({ url }) =>
    url.origin ===
      `${process.env.API_BASE_URL?.toString().slice(0, Math.max(0, process.env.API_BASE_URL.length - 1))}` && url.pathname.startsWith('/api/statistics/global-stat/'),

  new StaleWhileRevalidate({
    cacheName: 'global-stat-api',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({ maxEntries: 1 }), // Will cache maximum 1 requests.
    ],
  })
);

// Reusable function to register a route
function registerConnectivityRoute(indicator, isWeekly, cacheName,urlPath) {
  registerRoute(
    ({ url }) =>
      url.origin ===
        `${process.env.API_BASE_URL?.toString().slice(0, Math.max(0, process.env.API_BASE_URL.length - 1))}` &&
      url.pathname.startsWith(urlPath) &&
      url.search.split('&')[0] === `?indicator=${indicator}` &&
      url.search.split('&')[3] === `is_weekly=${isWeekly}`,

    new StaleWhileRevalidate({
      cacheName,
      plugins: [
        new CacheableResponsePlugin({
          statuses: [0, 200],
        }),
        new ExpirationPlugin({ maxEntries: 1 }), // Will cache maximum 1 request.
      ],
    })
  );
}

/**
 * Global view Connectivity Statistics api.
 *
 * Caches at: runtime
 */
// Register the weekly route for connectivity download
registerConnectivityRoute('download', 'true', 'connectivity-stat-api-download-weekly','/api/statistics/connectivity/');

// Register the monthly route for connectivity download
registerConnectivityRoute('download', 'false', 'connectivity-stat-api-download-monthly','/api/statistics/connectivity/');

// Register the weekly route for connectivity uptime
registerConnectivityRoute('uptime', 'true', 'connectivity-stat-api-uptime-weekly','/api/statistics/connectivity/');

// Register the monthly route for connectivity uptime
registerConnectivityRoute('uptime', 'false', 'connectivity-stat-api-uptime-monthly','/api/statistics/connectivity/');

// Register the weekly route for connectivity latency
registerConnectivityRoute('latency', 'true', 'connectivity-stat-api-latency-weekly','/api/statistics/connectivity/');

// Register the monthly route for connectivity latency
registerConnectivityRoute('latency', 'false', 'connectivity-stat-api-latency-monthly','/api/statistics/connectivity/');

/**
 * Country view Connectivity Statistics api.
 *
 * Caches at: runtime
 */

// Register the weekly route for country connectivity download
registerConnectivityRoute('download', 'true', 'country-connectivity-stat-api-download-weekly','/api/statistics/countryconnectivity/');

// Register the monthly route for country connectivity download
registerConnectivityRoute('download', 'false', 'country-connectivity-stat-api-download-monthly','/api/statistics/countryconnectivity/');

// Register the weekly route for country connectivity uptime
registerConnectivityRoute('uptime', 'true', 'country-connectivity-stat-api-uptime-weekly','/api/statistics/countryconnectivity/');

// Register the monthly route for country connectivity uptime
registerConnectivityRoute('uptime', 'false', 'country-connectivity-stat-api-uptime-monthly','/api/statistics/countryconnectivity/');

// Register the weekly route for country connectivity latency
registerConnectivityRoute('latency', 'true', 'country-connectivity-stat-api-latency-weekly','/api/statistics/countryconnectivity/');

// Register the monthly route for country connectivity latency
registerConnectivityRoute('latency', 'false', 'country-connectivity-stat-api-latency-monthly','/api/statistics/countryconnectivity/');

/**
 * Potential Coverage Statistics api.
 *
 * Caches at: runtime
 */

function registerCoverageRoute(cacheName,urlPath) {
  registerRoute(
    ({ url }) =>
      url.origin ===
        `${process.env.API_BASE_URL?.toString().slice(0, Math.max(0, process.env.API_BASE_URL.length - 1))}` &&
      url.pathname.startsWith(urlPath),

    new StaleWhileRevalidate({
      cacheName,
      plugins: [
        new CacheableResponsePlugin({
          statuses: [0, 200],
        }),
        new ExpirationPlugin({ maxEntries: 1 }), // Will cache maximum 1 request.
      ],
    })
  );
}

// Register the global view coverage route
registerCoverageRoute('potential-coverage-stat-api','/api/statistics/coverage/');

// Register the country view coverage route
registerCoverageRoute('country-potential-coverage-stat-api','/api/statistics/countrycoverage/');

/**
 * Random points api.
 *
 * Caches at: runtime
 */
registerRoute(
  ({ url }) =>
    url.origin ===
      `${process.env.API_BASE_URL?.toString().slice(
        0,
        Math.max(0, process.env.API_BASE_URL.length - 1)
      )}` && url.pathname.startsWith('/api/locations/schools/random/'),

  new StaleWhileRevalidate({
    cacheName: 'random-schools-api',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({ maxEntries: 1 }), // Will cache maximum 1 requests.
    ],
  })
);

/**
 * Random points api.
 *
 * Caches at: runtime
 */
registerRoute(
  ({ url }) =>
    url.origin ===
      `${process.env.API_BASE_URL?.toString().slice(
        0,
        Math.max(0, process.env.API_BASE_URL.length - 1)
      )}` && url.pathname.startsWith('/api/statistics/country/'),

  new StaleWhileRevalidate({
    cacheName: 'country-detail-api',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({ maxEntries: 200 }), // Will cache maximum 1 requests.
    ],
  })
);

/**
 * We use CacheFirst for images because, images are not going to change very often,
 * so it does not make sense to revalidate images on every request.
 *
 * @see https://developers.google.com/web/tools/workbox/guides/common-recipes#caching_images
 */
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// @see https://developers.google.com/web/tools/workbox/guides/common-recipes#cache_css_and_javascript_files
registerRoute(
  ({ request }) =>
    request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
);
